### ISSUE TITLE
Purge CSS is being applyed not only to tailwind

### ISSUE THREAD

**Issue by franciscolourenco** [forsartis/vue-cli-plugin-tailwind#1]
I'm using [Element UI](https://element.eleme.io) and `Tailwind`, both installed vie Vue-cli plugins.
However it seems the included purge-css plugin included is being applied to the global css and not only to Tailwind, stripping all the Element UI classes.

The postcss config in package.json looks like this:
```json
  "postcss": {
    "plugins": {
      "vue-cli-plugin-tailwind/purgecss": {},
      "tailwindcss": "./tailwind.config.js",
      "autoprefixer": {}
    }
```

Thanks!

**Comment by forsartis** [comment]
Which cli plugin do you use for Element and what options have you picked during plugin installation? Need the info so I can reproduce the issue.

**Comment by forsartis** [comment]
@franciscolourenco I looked a bit more into Purgecss configuration.
It seems, there is no easy way to run Purgecss only on Tailwind CSS.
However, it is possible to whitelist css selectors. For Element UI the following PostCSS config should work.

```javascript
// postcss.config.js
module.exports = {
  plugins: {
    tailwindcss: {},
    'vue-cli-plugin-tailwind/purgecss': {
      whitelistPatternsChildren: [/^el-/],
    },
    autoprefixer: {},
  },
};
```
See [Purgecss Configuration](https://www.purgecss.com/configuration#options) for more info.

Closing for now, if this is still an issue for you feel free to open it again.

**Comment by franciscolourenco** [comment]
Hi @forsartis thank you for looking into this. 

I've used https://github.com/ElementUI/vue-cli-plugin-element and chose these options:
- Fully import
- Overwrite variables: yes

I'm going to try your suggestion.

Have you looked into the "only" option?
https://github.com/FullHuman/purgecss-webpack-plugin#only

**Comment by franciscolourenco** [comment]
I'm using the default vue cli configuration defined in `package.json`. Do you know how I can define a regex in there? I'm getting the following error when I add the whitelist, I'm assuming that the plugin expects the whitelist elements to be regular expressions with the function `test`?

```
 error  in ./src/App.vue?vue&type=style&index=0&lang=scss&

Module build failed (from ./node_modules/mini-css-extract-plugin/dist/loader.js):
ModuleBuildError: Module build failed (from ./node_modules/postcss-loader/src/index.js):
TypeError: v.test is not a function
    at /Users/user/code/unio/web/src/App.vue:1:1
    at /Users/user/code/unio/web/node_modules/purgecss/lib/purgecss.js:1046:26
    at Array.some (<anonymous>)
    at Purgecss.isSelectorWhitelistedChildren (/Users/user/code/unio/web/node_modules/purgecss/lib/purgecss.js:1045:104)
    at Purgecss.shouldKeepSelector (/Users/user/code/unio/web/node_modules/purgecss/lib/purgecss.js:994:30)
    at /Users/user/code/unio/web/node_modules/purgecss/lib/purgecss.js:803:47
    at /Users/user/code/unio/web/node_modules/postcss-selector-parser/dist/selectors/container.js:224:26
    at Root.each (/Users/user/code/unio/web/node_modules/postcss-selector-parser/dist/selectors/container.js:207:22)
    at Root.walk (/Users/user/code/unio/web/node_modules/postcss-selector-parser/dist/selectors/container.js:223:21)
    at Processor.func (/Users/user/code/unio/web/node_modules/purgecss/lib/purgecss.js:764:33)
    at Processor._runSync (/Users/user/code/unio/web/node_modules/postcss-selector-parser/dist/processor.js:84:30)
    at Processor.processSync (/Users/user/code/unio/web/node_modules/postcss-selector-parser/dist/processor.js:177:27)
    at Purgecss.evaluateRule (/Users/user/code/unio/web/node_modules/purgecss/lib/purgecss.js:811:16)
    at /Users/user/code/unio/web/node_modules/purgecss/lib/purgecss.js:737:34
    at /Users/user/code/unio/web/node_modules/postcss/lib/container.js:135:18
    at Root.each (/Users/user/code/unio/web/node_modules/postcss/lib/container.js:101:16)
    at Root.walk (/Users/user/code/unio/web/node_modules/postcss/lib/container.js:131:17)
    at runLoaders (/Users/user/code/unio/web/node_modules/webpack/lib/NormalModule.js:301:20)
    at /Users/user/code/unio/web/node_modules/loader-runner/lib/LoaderRunner.js:367:11
    at /Users/user/code/unio/web/node_modules/loader-runner/lib/LoaderRunner.js:233:18
    at context.callback (/Users/user/code/unio/web/node_modules/loader-runner/lib/LoaderRunner.js:111:13)
    at Promise.resolve.then.then.catch (/Users/user/code/unio/web/node_modules/postcss-loader/src/index.js:208:9)
    at <anonymous>

 @ ./src/App.vue?vue&type=style&index=0&lang=scss& 1:0-482 1:498-501 1:503-982 1:503-982
 @ ./src/App.vue
 @ ./src/main.js
 @ multi ./src/main.js
```

**Comment by forsartis** [comment]
I would suggest using a `postcss.config.js` file. That way you are not limited to JSON-compatible values. Of course, it would be nice if purgecss would convert strings into regex, but I see you already opened an issue about it there.

**Comment by franciscolourenco** [comment]
Thanks. I though vuecli always used package.json but I realize now it is an option during scaffolding.
