### ISSUE TITLE
Support for Typescript

### ISSUE THREAD

**Issue by khalyomede** [forsartis/vue-cli-plugin-tailwind#15]
This is the error that I get when calling `vue add tailwindcss`  in a Typescript configured vue-cli project:

```bash
�🚀  Invoking generator for vue-cli-plugin-tailwindcss...
-  Running completion hooks... ERROR  Error: ENOENT: no such file or directory, open 'C:\Users\Khaly\translate-it\src\main.js'
Error: ENOENT: no such file or directory, open 'C:\Users\Khaly\translate-it\src\main.js'
    at Object.openSync (fs.js:440:3)
    at Object.readFileSync (fs.js:342:35)
    at C:\Users\Khaly\translate-it\node_modules\vue-cli-plugin-tailwindcss\generator\index.js:30:30
    at runGenerator (C:\Users\Khaly\AppData\Local\Yarn\Data\global\node_modules\@vue\cli\lib\invoke.js:132:13)
    at processTicksAndRejections (internal/process/task_queues.js:94:5)
    at async invoke (C:\Users\Khaly\AppData\Local\Yarn\Data\global\node_modules\@vue\cli\lib\invoke.js:92:3)
```

I do not have an `src/main.js` but a `src/main.ts` file.

**Comment by khalyomede** [comment]
Sorry wrong repo ^^'

**Comment by nour-dev** [comment]
same issue . how to fix @khalyomede ?

**Comment by khalyomede** [comment]
Was a while ago, but as far as I remember I used bare tailwindcss within my SFCs. The code is here fyi: https://github.com/khalyomede/translate-it.
